VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# define vagrant box to use
	config.vm.box = "ubuntu/trusty64"
    config.ssh.forward_agent = true

	# VirtualBox configuration
	config.vm.provider :virtualbox do |v|
		v.name = "devVM"
		v.memory = 1024
		v.cpus = 2
	end

	# define static IP
	config.vm.hostname = "devVM"
	config.vm.network :private_network, ip: "192.168.56.102"

	# define port-forwarding
	config.vm.network :forwarded_port, guest: 8000, host: 80, auto_correct: true

	# folders to sync with the host
	config.vm.synced_folder ".", "/home/vagrant/vued3-barchart", { :mount_options => ['dmode=777','fmode=777'] }
end
